import { describe, expect, it, vi } from 'vitest';
import { PokerTable } from '../../../packages/engine/src/index';
import { hasRecoverablePdhCheckpoint, pdhMatchHandler } from '../src/pdhMatch';
import {
  accountingWrites,
  rpcPlayerProfile,
  rpcFreeTopUp,
  rpcPlayerReport,
  rpcAdminAccess,
  withProfileTransaction,
} from '../src/playerProfiles';
import {
  canAccessTable,
  grantTableAccess,
  protectTableStorageList,
  protectTableStorageRead,
} from '../src/tableAccess';

function store() {
  const data = new Map<string, any>();
  const key = (o: any) => `${o.collection}/${o.userId}/${o.key}`;
  const nk: any = {
    accountGetId: () => ({ email: 'player@example.test' }),
    storageRead: (items: any[]) =>
      items
        .map((o) => data.get(key(o)))
        .filter(Boolean)
        .map((o) => structuredClone(o)),
    storageWrite: (items: any[]) => {
      // Match Nakama's all-or-nothing version-checked storage batch.
      for (const o of items) {
        const prev = data.get(key(o));
        if (
          (o.version === '*' && prev) ||
          (o.version && o.version !== '*' && o.version !== prev?.version)
        )
          throw Error('storage version conflict');
      }
      for (const o of items)
        data.set(key(o), {
          ...structuredClone(o),
          version: String(Number(data.get(key(o))?.version ?? 0) + 1),
        });
      return items.map((o) => data.get(key(o)));
    },
    storageList: (_id: string, collection: string) => ({
      objects: [...data.values()].filter((o) => o.collection === collection),
    }),
  };
  const profile = (id = 'p1') => JSON.parse(rpcPlayerProfile({ userId: id }, null, nk, '{}'));
  return { nk, data, profile };
}

describe('persistent free-play profiles', () => {
  it('persists a repaired all-in blind turn, serves refreshes, and settles the same hand once', () => {
    const { nk, data, profile } = store();
    profile('p1');
    profile('p2');
    const ctx = { env: { PDH_ENABLE_PLAYER_PROFILES: 'true' } };
    const logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    const dispatcher = { broadcastMessage: vi.fn() };
    nk.binaryToString = (value: Uint8Array) => new TextDecoder().decode(value);
    let state = pdhMatchHandler.matchInit(ctx, logger, nk, { tableId: 'SHORT' }).state;
    const table = new PokerTable('SHORT');
    table.seatPlayer(0, { id: 'p1', name: 'Short blind', stack: 1 });
    table.seatPlayer(1, { id: 'p2', name: 'Opponent', stack: 10000 });
    table.startHand(() => 0.1);
    const handId = table.state.hand!.handId;
    // Reproduce the persisted state generated by the old one-chip blind bug.
    table.state.hand!.pendingNextPhaseAt = null;
    table.state.hand!.actionOnSeat = 0;
    table.state.hand!.actionDeadline = Date.now() - 1;
    nk.storageWrite(accountingWrites(nk, state.table, table.state, state.stateVersion));
    state.table = table.state;
    const presences = ['p1', 'p2'].map((userId) => ({ userId, sessionId: userId }));
    state.presences = Object.fromEntries(presences.map((p) => [`${p.userId}:${p.sessionId}`, p]));
    const tick = (time: number, refresh = false) => {
      const now = vi.spyOn(Date, 'now').mockReturnValue(time);
      try {
        state = pdhMatchHandler.matchLoop(
          ctx,
          logger,
          nk,
          dispatcher,
          1,
          state,
          refresh
            ? presences.map((sender) => ({
                sender,
                opCode: 1,
                data: new TextEncoder().encode(JSON.stringify({ v: 1, type: 'requestState' })),
              }))
            : []
        ).state;
      } finally {
        now.mockRestore();
      }
    };
    tick(Date.now());
    expect(state.table.hand!.pendingNextPhaseAt).not.toBeNull();
    const saved = () =>
      data.get('pdh_match_checkpoints/00000000-0000-0000-0000-000000000000/SHORT').value;
    expect(saved().stateVersion).toBe(state.stateVersion);
    tick(state.table.hand!.pendingNextPhaseAt + 1, true);
    for (let i = 0; i < 3; i++) {
      expect(state.table.hand!.phase).toBe('discard');
      tick(state.table.hand!.discardDeadline + 1, true);
    }
    expect(state.table.hand!.handId).toBe(handId);
    expect(state.table.hand!.phase).toBe('showdown');
    const total = ['p1', 'p2'].reduce((sum, id) => {
      const p = profile(id);
      return sum + p.availableChips + (p.allocation?.chips ?? 0);
    }, 0);
    expect(total).toBe(20000);
    expect(profile('p1').handsCompleted).toBe(1);
    expect(profile('p2').handsCompleted).toBe(1);
    tick(Date.now(), true);
    expect(profile('p1').handsCompleted).toBe(1);
    expect(logger.error).not.toHaveBeenCalled();
    const snapshots = dispatcher.broadcastMessage.mock.calls
      .map((call) => JSON.parse(call[1] as string))
      .filter((m) => m.type === 'state' && m.state.hand?.phase === 'showdown');
    expect(new Set(snapshots.map((m) => m.state.you.playerId))).toEqual(new Set(['p1', 'p2']));
    expect(new Set(snapshots.map((m) => m.state.hand.handId))).toEqual(new Set([handId]));
  });
  it('grants administration only to allowlisted email account IDs, without changing profiles', () => {
    const { nk, data, profile } = store();
    profile('alex-id');
    profile('brad-id');
    profile('regular-id');
    const before = structuredClone([...data]);
    const env = { PDH_ADMIN_USER_IDS: ' alex-id,brad-id ' };
    for (const userId of ['alex-id', 'brad-id']) {
      expect(JSON.parse(rpcAdminAccess({ userId, env }, null, nk))).toMatchObject({
        authorized: true,
        userId,
      });
      expect(() => rpcPlayerReport({ userId, env }, null, nk, '{}')).not.toThrow();
    }
    for (const ctx of [
      { userId: 'regular-id', username: 'Alex', env },
      { userId: 'alex-id', env: {} },
      { env },
    ]) {
      expect(JSON.parse(rpcAdminAccess(ctx, null, nk))).toEqual({ authorized: false });
      expect(() => rpcPlayerReport(ctx, null, nk, '{}')).toThrow();
    }
    expect([...data]).toEqual(before);
    nk.accountGetId = () => ({});
    expect(() => rpcAdminAccess({ userId: 'alex-id', env }, null, nk)).toThrow(/email/);
  });
  it('recovers an expired settled checkpoint only while every funded allocation still matches', () => {
    const { nk, data, profile } = store();
    profile();
    const table = new PokerTable('OVERNIGHT').state;
    const empty = structuredClone(table);
    table.seats[0] = {
      id: 'p1',
      name: 'Alex',
      seat: 0,
      stack: 10000,
      buyInTotal: 10000,
      rebuyCount: 0,
    };
    nk.storageWrite(accountingWrites(nk, empty, table, 1));
    const checkpoint = {
      schemaVersion: 1,
      tableId: table.id,
      matchId: 'old-match',
      stateVersion: 1,
      writtenAtMs: 1,
      expiresAtMs: 2,
      privateState: { tableState: table, replayEvents: [] },
      recovery: { policy: 'restore_from_checkpoint', canRestore: true },
      playerConnections: {},
    };
    nk.storageWrite([
      {
        collection: 'pdh_match_checkpoints',
        key: table.id,
        userId: '00000000-0000-0000-0000-000000000000',
        value: checkpoint,
      },
    ]);
    expect(hasRecoverablePdhCheckpoint(nk, table.id)).toBe(true);
    const stored = data.get('pdh_player_profiles/p1/profile');
    stored.value.allocation.chips = 9000;
    expect(hasRecoverablePdhCheckpoint(nk, table.id)).toBe(false);
    stored.value.allocation.chips = 10000;
    stored.value.allocation.tableId = 'ANOTHER';
    expect(hasRecoverablePdhCheckpoint(nk, table.id)).toBe(false);
    stored.value.allocation.tableId = table.id;
    const saved = data.get(
      `pdh_match_checkpoints/00000000-0000-0000-0000-000000000000/${table.id}`
    );
    saved.value.privateState.tableState.hand = { phase: 'betting' };
    expect(hasRecoverablePdhCheckpoint(nk, table.id)).toBe(false);
    saved.value.privateState.tableState.hand = null;
    stored.value.allocation = null;
    expect(hasRecoverablePdhCheckpoint(nk, table.id)).toBe(false);
  });
  it('preserves a concurrent top-up when retrying the accounting commit without replaying play', () => {
    const { nk, profile } = store();
    profile();
    const write = nk.storageWrite;
    let injectConflict = true;
    nk.storageWrite = (items: any[]) => {
      if (injectConflict) {
        injectConflict = false;
        rpcFreeTopUp(
          { userId: 'p1' },
          null,
          nk,
          JSON.stringify({ requestId: 'concurrent-topup-00001' })
        );
      }
      return write(items);
    };
    const callback = vi.fn((_ctx, _log, runtime, _dispatcher, _tick, state) => {
      state.table.seats[0] = { id: 'p1', name: 'Alex', seat: 0, stack: 10000, buyInTotal: 10000 };
      state.stateVersion = 1;
      runtime.storageWrite([
        {
          collection: 'pdh_match_checkpoints',
          key: 'RACE',
          userId: '00000000-0000-0000-0000-000000000000',
          value: state,
        },
      ]);
      return { state };
    });
    const result = withProfileTransaction(callback)(
      { env: { PDH_ENABLE_PLAYER_PROFILES: 'true' } },
      { error: vi.fn() },
      nk,
      { broadcastMessage: vi.fn() },
      1,
      { table: new PokerTable('RACE').state, stateVersion: 0 }
    );
    expect(result.state.stateVersion).toBe(1);
    expect(callback).toHaveBeenCalledTimes(1);
    expect(profile()).toMatchObject({
      availableChips: 10000,
      freeTopUps: 1,
      freeChipsGranted: 20000,
      allocation: { chips: 10000 },
    });
  });
  it('ignores reordered storage keys without issuing duplicate ledger receipts', () => {
    const { nk, data, profile } = store();
    profile();
    const before = new PokerTable('ORDER').state;
    const after = structuredClone(before);
    after.seats[0] = {
      id: 'p1',
      name: 'Alex',
      seat: 0,
      stack: 10000,
      buyInTotal: 10000,
      rebuyCount: 0,
    };
    nk.storageWrite(accountingWrites(nk, before, after, 1));
    const stored = data.get('pdh_player_profiles/p1/profile');
    const allocation = stored.value.allocation;
    stored.value.allocation = {
      chips: allocation.chips,
      rebuyCount: allocation.rebuyCount,
      tableId: allocation.tableId,
      buyInTotal: allocation.buyInTotal,
    };
    const valueBefore = structuredClone(stored.value);
    expect(accountingWrites(nk, after, after, 1)).toEqual([]);
    expect(stored.value).toEqual(valueBefore);
    const empty = structuredClone(after);
    empty.seats.fill(null);
    nk.storageWrite(accountingWrites(nk, after, empty, 2));
    expect(accountingWrites(nk, empty, empty, 2)).toEqual([]);
    expect(profile()).toMatchObject({
      availableChips: 10000,
      allocation: null,
      tableSessions: 1,
      netWinnings: 0,
    });
  });

  it('retains a failed departure and refunds exactly once after storage recovers', () => {
    const { nk, profile } = store();
    profile();
    nk.binaryToString = (data: Uint8Array) => new TextDecoder().decode(data);
    const ctx = { matchId: 'recovery-match', env: { PDH_ENABLE_PLAYER_PROFILES: 'true' } };
    const log = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    const dispatcher = { broadcastMessage: vi.fn() };
    const presence = { userId: 'p1', sessionId: 's1' };
    let state = pdhMatchHandler.matchInit(ctx, log, nk, { tableId: 'RECOVER' }).state;
    state = pdhMatchHandler.matchJoin(ctx, log, nk, dispatcher, 1, state, [presence]).state;
    state = pdhMatchHandler.matchLoop(ctx, log, nk, dispatcher, 2, state, [
      {
        opCode: 1,
        sender: presence,
        data: new TextEncoder().encode(
          JSON.stringify({ v: 1, type: 'join', name: 'Alex', buyIn: 10000 })
        ),
      },
    ]).state;
    expect(profile().allocation?.chips).toBe(10000);
    const write = nk.storageWrite;
    nk.storageWrite = () => {
      throw Error('database unavailable');
    };
    const version = state.stateVersion;
    state = pdhMatchHandler.matchLeave(ctx, log, nk, dispatcher, 3, state, [presence]).state;
    expect(Object.values(state.presences)).toHaveLength(0);
    expect(state.pendingDepartures).toHaveLength(1);
    expect(state.stateVersion).toBe(version);
    expect(profile().allocation?.chips).toBe(10000);
    nk.storageWrite = write;
    state = pdhMatchHandler.matchLoop(ctx, log, nk, dispatcher, 4, state, []).state;
    expect(state.pendingDepartures).toBeUndefined();
    const clock = vi.spyOn(Date, 'now').mockReturnValue(Date.now() + 20000);
    try {
      state = pdhMatchHandler.matchLoop(ctx, log, nk, dispatcher, 5, state, []).state;
      state = pdhMatchHandler.matchLoop(ctx, log, nk, dispatcher, 6, state, []).state;
      expect(profile()).toMatchObject({
        availableChips: 10000,
        allocation: null,
        tableSessions: 1,
      });
    } finally {
      clock.mockRestore();
    }
  });
  it('requires email and grants the welcome balance exactly once', () => {
    const { nk, profile } = store();
    expect(profile().availableChips).toBe(10000);
    expect(profile().availableChips).toBe(10000);
    nk.accountGetId = () => ({});
    expect(() => profile()).toThrow('email/password');
  });

  it('allows unlimited distinct top-ups but deduplicates retries', () => {
    const { nk, profile } = store();
    profile();
    for (const requestId of ['request-00000000001', 'request-00000000001', 'request-00000000002']) {
      rpcFreeTopUp({ userId: 'p1' }, null, nk, JSON.stringify({ requestId, amount: 999999 }));
    }
    expect(profile()).toMatchObject({
      availableChips: 30000,
      freeTopUps: 2,
      freeChipsGranted: 30000,
    });
  });

  it('transfers table chips, records winnings and hands once, then returns chips on exit', () => {
    const { nk, profile } = store();
    profile();
    profile('p2');
    const before = new PokerTable('ABC234').state;
    const after = structuredClone(before);
    after.seats[0] = {
      id: 'p1',
      name: 'Alex',
      seat: 0,
      stack: 10000,
      buyInTotal: 10000,
      rebuyCount: 0,
    };
    after.seats[1] = {
      id: 'p2',
      name: 'Brad',
      seat: 1,
      stack: 10000,
      buyInTotal: 10000,
      rebuyCount: 0,
    };
    nk.storageWrite(accountingWrites(nk, before, after, 1));
    expect(profile()).toMatchObject({ availableChips: 0, tableSessions: 1 });
    const settled = structuredClone(after);
    settled.seats[0]!.stack = 11000;
    settled.seats[1]!.stack = 9000;
    settled.hand = {
      handId: 'h1',
      phase: 'showdown',
      players: [{ id: 'p1' }, { id: 'p2' }],
      showdownWinners: [{ playerId: 'p1', amount: 2000 }],
    } as any;
    nk.storageWrite(accountingWrites(nk, after, settled, 2));
    nk.storageWrite(accountingWrites(nk, settled, settled, 3));
    expect(profile()).toMatchObject({
      netWinnings: 1000,
      handsStarted: 1,
      handsCompleted: 1,
      handsWon: 1,
    });
    expect(profile('p2').netWinnings).toBe(-1000);
    const empty = structuredClone(settled);
    empty.seats.fill(null);
    nk.storageWrite(accountingWrites(nk, settled, empty, 4));
    expect(profile()).toMatchObject({ availableChips: 11000, allocation: null });
    expect(profile('p2').availableChips).toBe(9000);
  });

  it('blocks spending the same balance at two tables and requires funded rebuys', () => {
    const { nk, profile } = store();
    profile();
    const empty = new PokerTable('A').state;
    const seated = structuredClone(empty);
    seated.seats[0] = {
      id: 'p1',
      name: 'Alex',
      seat: 0,
      stack: 10000,
      buyInTotal: 10000,
      rebuyCount: 0,
    };
    nk.storageWrite(accountingWrites(nk, empty, seated, 1));
    expect(() => accountingWrites(nk, empty, { ...seated, id: 'B' }, 2)).toThrow('other table');
    const busted = structuredClone(seated);
    busted.seats[0]!.stack = 0;
    nk.storageWrite(accountingWrites(nk, seated, busted, 2));
    const rebought = structuredClone(busted);
    Object.assign(rebought.seats[0]!, { stack: 10000, buyInTotal: 20000, rebuyCount: 1 });
    expect(() => accountingWrites(nk, busted, rebought, 3)).toThrow('Not enough chips');
    rpcFreeTopUp({ userId: 'p1' }, null, nk, JSON.stringify({ requestId: 'request-00000000001' }));
    nk.storageWrite(accountingWrites(nk, busted, rebought, 3));
    expect(profile()).toMatchObject({
      availableChips: 0,
      freeTopUps: 1,
      tableRebuys: 1,
      netWinnings: -10000,
    });
  });

  it('rejects concurrent grants atomically without writing a receipt', () => {
    const { nk, profile, data } = store();
    profile();
    const write = nk.storageWrite;
    nk.storageWrite = (items: any[]) => {
      const p = [...data.values()].find((o) => o.collection === 'pdh_player_profiles');
      p.version = '99';
      return write(items);
    };
    expect(() =>
      rpcFreeTopUp({ userId: 'p1' }, null, nk, JSON.stringify({ requestId: 'request-00000000001' }))
    ).toThrow('version conflict');
    expect(profile().availableChips).toBe(10000);
    expect([...data.values()].filter((o) => o.key.startsWith('topup:'))).toHaveLength(0);
  });

  it('does not publish or retain an in-memory mutation when persistence fails', () => {
    const { nk, profile } = store();
    profile();
    const original = { table: new PokerTable('A').state, stateVersion: 0 };
    const broadcastMessage = vi.fn();
    const callback = (
      _ctx: any,
      _log: any,
      runtime: any,
      dispatcher: any,
      _tick: number,
      state: any
    ) => {
      state.table.seats[0] = { id: 'p1', name: 'Alex', seat: 0, stack: 10000, buyInTotal: 10000 };
      state.stateVersion++;
      runtime.storageWrite([
        {
          collection: 'pdh_match_checkpoints',
          key: 'A',
          userId: '00000000-0000-0000-0000-000000000000',
          value: state,
          permissionRead: 0,
          permissionWrite: 0,
        },
      ]);
      dispatcher.broadcastMessage(2, 'unsafe state');
      return { state };
    };
    nk.storageWrite = () => {
      throw Error('database unavailable');
    };
    const result = withProfileTransaction(callback)(
      { env: { PDH_ENABLE_PLAYER_PROFILES: 'true' } },
      { error: vi.fn() },
      nk,
      { broadcastMessage },
      1,
      original
    );
    expect(result.state).toBe(original);
    expect(original.table.seats[0]).toBeNull();
    expect(broadcastMessage.mock.calls.flat()).not.toContain('unsafe state');
    expect(profile().availableChips).toBe(10000);
  });

  it('restricts operator reports to configured administrators', () => {
    const { nk, profile } = store();
    profile();
    expect(() => rpcPlayerReport({ userId: 'p1' }, null, nk, '{}')).toThrow('administrators');
    const report = JSON.parse(
      rpcPlayerReport({ userId: 'p1', env: { PDH_ADMIN_USER_IDS: 'p1' } }, null, nk, '{}')
    );
    expect(report.players).toHaveLength(1);
    expect(report.players[0].playerId).toBe('p1');
  });
});

describe('code-only table access', () => {
  it('requires code admission before direct match entry', () => {
    const { nk } = store();
    nk.storageWrite([
      {
        collection: 'tables',
        key: 'ABC234',
        userId: '00000000-0000-0000-0000-000000000000',
        value: { isPrivate: true },
      },
    ]);
    expect(canAccessTable(nk, 'p1', 'ABC234')).toBe(false);
    grantTableAccess(nk, 'p1', 'ABC234');
    expect(canAccessTable(nk, 'p1', 'ABC234')).toBe(true);
    expect(canAccessTable(nk, 'p2', 'ABC234')).toBe(false);
  });
  it('blocks direct reads of legacy public metadata and private checkpoints', () => {
    expect(() =>
      protectTableStorageRead(null, null, null, { objectIds: [{ collection: 'tables' }] })
    ).toThrow();
    expect(() =>
      protectTableStorageList(null, null, null, { collection: 'pdh_match_checkpoints' })
    ).toThrow();
    expect(protectTableStorageList(null, null, null, { collection: 'other' })).toEqual({
      collection: 'other',
    });
  });
});
